import { FormattedUtxo } from '../../types'

export const accountUtxos: FormattedUtxo[] = [
  // Native SegWit UTXOs
  {
    txId: 'native_tx1',
    outputIndex: 0,
    satoshis: 75000,
    address: 'bcrt1qcr8te4kr609gcawutmrza0j4xv80jy8zeqchgx',
    inscriptions: [],
    confirmations: 1,
    scriptPk: 'mock_script1',
    runes: {},
    alkanes: {},
    indexed: false,
  },
  {
    txId: 'native_tx2',
    outputIndex: 0,
    satoshis: 50000,
    address: 'bcrt1qcr8te4kr609gcawutmrza0j4xv80jy8zeqchgx',
    inscriptions: [],
    confirmations: 1,
    scriptPk: 'mock_script2',
    runes: {},
    alkanes: {},
    indexed: false,
  },
  // Nested SegWit UTXOs
  {
    txId: 'nested_tx1',
    outputIndex: 0,
    satoshis: 100000,
    address: '2N1LGaGg836mqSQqiuUBLfcyGBhyZbremDX',
    inscriptions: [],
    confirmations: 1,
    scriptPk: 'mock_script3',
    runes: {},
    alkanes: {},
    indexed: false,
  },
  {
    txId: 'nested_tx2',
    outputIndex: 0,
    satoshis: 25000,
    address: '2N1LGaGg836mqSQqiuUBLfcyGBhyZbremDX',
    inscriptions: [],
    confirmations: 1,
    scriptPk: 'mock_script4',
    runes: {},
    alkanes: {},
    indexed: false,
  },
  // Taproot UTXOs
  {
    txId: 'taproot_tx1',
    outputIndex: 0,
    satoshis: 150000,
    address: 'bcrt1pklamaklxrdgm7njpudghhq3j7vwxfuak0l7jmrhvluf0cld5etjsga00nj',
    inscriptions: [],
    confirmations: 1,
    scriptPk: 'mock_script5',
    runes: {},
    alkanes: {},
    indexed: false,
  },
  {
    txId: 'taproot_tx2',
    outputIndex: 0,
    satoshis: 50000,
    address: 'bcrt1pklamaklxrdgm7njpudghhq3j7vwxfuak0l7jmrhvluf0cld5etjsga00nj',
    inscriptions: [],
    confirmations: 1,
    scriptPk: 'mock_script6',
    runes: {},
    alkanes: {},
    indexed: false,
  },
  // Legacy UTXOs
  {
    txId: 'legacy_tx1',
    outputIndex: 0,
    satoshis: 200000,
    address: 'mipcBbFg9gMiCh81Kj8tqqdgoZub1ZJRfn',
    inscriptions: [],
    confirmations: 1,
    scriptPk: 'mock_script7',
    runes: {},
    alkanes: {},
    indexed: false,
  },
  {
    txId: 'legacy_tx2',
    outputIndex: 0,
    satoshis: 100000,
    address: 'mipcBbFg9gMiCh81Kj8tqqdgoZub1ZJRfn',
    inscriptions: [],
    confirmations: 1,
    scriptPk: 'mock_script8',
    runes: {},
    alkanes: {},
    indexed: false,
  },
] 